# Generated by Django 5.1.4 on 2025-06-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosaRiwayat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('usia', models.IntegerField()),
                ('jenis_kelamin', models.CharField(max_length=10)),
                ('gejala', models.TextField()),
                ('hasil', models.CharField(max_length=100)),
                ('saran', models.TextField()),
                ('waktu', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
